_security_logout:
    resource: security.route_loader.logout
    type: service

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
