name: Building
on: 
  push:
    branches:
      - main

jobs:
  deployment:
    name: Building
    runs-on: ubuntu-latest
    container:
      image: composer:latest
      volumes:
        - ${{ github.workspace }}:/app
    steps: 
    - name: Check out the repository
      uses: actions/checkout@v2
    - name: Running composer install
      run: composer install
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - uses: actions/checkout@v4
    - name: Build the Docker image
      uses: docker/build-push-action@v3
      with:
        file: Dockerfile
        push: false
        tags: user/app:latest

    - name: Send Telegram Notification on Success
      if: success()
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        curl -s -X POST https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage \
        -d chat_id=${TELEGRAM_CHAT_ID} \
        -d text="✅ Building workflow succeeded for commit` ${{ github.sha }} ` on branch ${{ github.ref }}"
      continue-on-error: false

    - name: Send Telegram Notification on Failure
      if: failure()
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        curl -s -X POST https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage \
        -d chat_id=${TELEGRAM_CHAT_ID} \
        -d text="❌ Building workflow failed for commit` ${{ github.sha }} ` on branch ${{ github.ref }}"
      continue-on-error: false
