name: Containerisation
on: 
  push:
    branches:
      - main

jobs:
  deployment:
    name: Containerisation
    runs-on: ubuntu-latest
    container:
      image: composer:latest
      volumes:
        - ${{ github.workspace }}:/app
    steps: 
    - name: Check out the repository
      uses: actions/checkout@v2
    - name: Running composer install
      run: composer install
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Pull Docker image with Symfony environment
      run: docker pull ghcr.io/symfonycasts/php:7.4-fpm

    - name: Build and push Docker image
      run: |
        docker tag ghcr.io/symfonycasts/php:7.4-fpm ${{ secrets.DOCKER_USERNAME }}/yourimage:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/yourimage:latest
     

