name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: vegetables-market
          POSTGRES_USER: ${{ secrets.DB_USERNAME }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, intl, pdo, pdo_pgsql

    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Copy .env file
      run: cp .env.test .env1

    - name: Run database migrations
      run: php bin/console doctrine:migrations:migrate --no-interaction

    - name: Build Docker image
      run: docker build -t skeleton-vegetables .

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_KEY }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Tag Docker image
      run: docker tag my-symfony-app:latest ${{ secrets.DOCKER_USERNAME }}/my-symfony-app:latest

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/my-symfony-app:latest
      
    - name: Run Docker container
      run: docker run -d -p 80:80 --name skeleton-vegetables skeleton-vegetables

    - name: Send Telegram Notification on Success
      if: success()
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        curl -s -X POST https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage \
        -d chat_id=${TELEGRAM_CHAT_ID} \
        -d text="✅ Build for containerization succeeded for commit ${{ github.sha }} on branch ${{ github.ref }}"
      continue-on-error: false

    - name: Send Telegram Notification on Failure
      if: failure()
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        curl -s -X POST https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage \
        -d chat_id=${TELEGRAM_CHAT_ID} \
        -d text="❌ Build for containerization failed for commit ${{ github.sha }} on branch ${{ github.ref }}"
      continue-on-error: false
