name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: vegetables-market
          POSTGRES_USER: ${{ secrets.DB_USERNAME }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, intl, pdo, pdo_pgsql

    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Copy .env file
      run: cp .env.test .env

    - name: Run database migrations
      run: php bin/console doctrine:migrations:migrate --no-interaction

    - name: Run tests
      run: php bin/phpunit

    - name: Build Docker image
      run: docker build -t my-symfony-app .

    - name: Run Docker container
      run: docker run -d -p 80:80 --name my-symfony-app my-symfony-app
