name: Containerisation
on: 
  push:
    branches:
      - main

jobs:
  deployment:
    name: Containerisation
    runs-on: ubuntu-latest
    container:
      image: composer:latest
      volumes:
        - ${{ github.workspace }}:/app
    steps: 
    - name: Check out the repository
      uses: actions/checkout@v2
    - name: Running composer install
      run: composer install
      
    - name: Build Docker image
      run: docker build -t skeleton-vegetables

    - name: Log in to Docker Hub
      run: echo ${{ secrets.DOCKER_KEY }} | docker login -u chickenshrimp --password-stdin

    - name: Create Docker Tag
      run: docker tag skeleton-vegetables chickenshrimp/skeleton-vegetables
      
    - name: Push to Docker Hub
      run: docker push chickenshrimp/skeleton-vegetables

