name: Containerisation
on: 
  push:
    branches:
      - main

jobs:
  deployment:
    name: Containerisation
    runs-on: ubuntu-latest
    container:
      image: composer:latest
      volumes:
        - ${{ github.workspace }}:/app
    steps: 
    - name: Check out the repository
      uses: actions/checkout@v2
    - name: Running composer install
      run: composer install
    - name: Running server
      run: symfony server:start

     

