name: Containerisation
on: 
  push:
    branches:
      - main

jobs:
  deployment:
    name: Containerisation
    runs-on: ubuntu-latest
    container:
      image: composer:latest
      volumes:
        - ${{ github.workspace }}:/app
    steps: 
    - name: Check out the repository
      uses: actions/checkout@v2
    - name: Running composer install
      run: composer install
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - uses: actions/checkout@v4
    - name: Build the Docker image
      uses: docker/build-push-action@v3
      with:
        file: Dockerfile
        push: false
        tags: user/app:latest
